FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV USER=devuser

RUN echo "Install essential packages"
RUN apt update && apt install -y \
    sudo bash git curl wget unzip build-essential \
    gnupg software-properties-common \
    ninja-build g++ gcc \
    python3 python3-pip python3-venv
    # && rm -rf /var/lib/apt/lists/*

RUN echo "Install CMake"
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | gpg --dearmor -o /usr/share/keyrings/kitware-archive-keyring.gpg && \
    echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ jammy main' \
        > /etc/apt/sources.list.d/kitware.list && \
    apt-get update && \
    apt-get install -y cmake

RUN echo "Install dev dependencies"
RUN apt-get update && apt-get install -y wget gnupg lsb-release
# Add LLVM apt key and repo
RUN wget https://apt.llvm.org/llvm.sh -O /tmp/llvm.sh && \
    chmod +x /tmp/llvm.sh && \
    /tmp/llvm.sh 19 && \
    ln -sf /usr/bin/clangd-19 /usr/bin/clangd

RUN echo "Create a dev user"
ARG USERNAME=devuser
ARG USER_UID=1000
ARG USER_GID=1000

RUN echo "Create user" 
RUN groupadd --gid $USER_GID $USERNAME || groupadd --gid 1001 $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME


RUN echo "Install Conan"
RUN pip3 install conan

RUN chsh -s /bin/bash $USERNAME

USER $USERNAME
WORKDIR /workspace
